# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-01 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenityId', models.AutoField(primary_key=True, serialize=False)),
                ('transport', models.BooleanField(default=False)),
                ('meals', models.BooleanField(default=True)),
                ('hotels', models.BooleanField(default=True)),
                ('sightSeeing', models.BooleanField(default=True)),
                ('inTransitMeals', models.BooleanField(default=False)),
                ('isFlight', models.BooleanField(default=False)),
                ('isTrain', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Amenity',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('providerCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Categories')),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider')),
            ],
            options={
                'db_table': 'ProviderCategory',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('tripId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('shortDescription', models.CharField(max_length=500)),
                ('longDescription', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=False)),
                ('amount1', models.IntegerField()),
                ('amount2', models.IntegerField()),
                ('onDiscount', models.BooleanField(default=False)),
                ('days', models.IntegerField()),
                ('departureDate', models.DateTimeField()),
                ('arrivalDate', models.DateTimeField()),
                ('departureCities', models.CharField(max_length=255)),
                ('arrivalCities', models.CharField(max_length=255)),
                ('itineraryId', models.CharField(max_length=255)),
                ('isInternational', models.BooleanField(default=False)),
                ('cities', models.CharField(max_length=500)),
                ('amenityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Amenity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Categories')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.CompanyUser')),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider')),
            ],
            options={
                'db_table': 'Trip',
            },
        ),
    ]
